(function () {
  const existingData = JSON.parse(localStorage.getItem("serveEaseData")) || {};

  const updatedCategories = [
  {
    id: "home-cleaning",
    name: "Home Cleaning",
    icon: "🧹",
    bgImage: "https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=900&q=80",
    subServices: ["Full Home Cleaning", "Kitchen Cleaning", "Bathroom Cleaning"]
  },
  {
    id: "salon-at-home",
    name: "Salon at Home",
    icon: "💇",
    bgImage: "https://images.unsplash.com/photo-1521590832167-7bcbfaa6381f?auto=format&fit=crop&w=900&q=80",
    subServices: ["Haircut & Styling", "Facial & Cleanup", "Manicure & Pedicure"]
  },
  {
    id: "plumbing",
    name: "Plumbing",
    icon: "🔧",
    bgImage: "assets/images/plumbing-category-realistic.jpeg",
    subServices: ["Plumbing"]
  },
  {
    id: "electrician",
    name: "Electrician",
    icon: "⚡",
    bgImage: "https://images.unsplash.com/photo-1621905251189-08b45d6a269e?auto=format&fit=crop&w=900&q=80",
    subServices: ["Electrician"]
  },
  {
    id: "appliance-repair-installation",
    name: "Appliance Repair / Installation",
    icon: "🛠",
    bgImage: "assets/images/appliance-repair-realistic.jpg",
    subServices: [
      "Washing Machine",
      "Refrigerator",
      "TV",
      "Geyser",
      "Chimney",
      "Laptop/Desktop",
      "AC"
    ]
  },
  {
    id: "pest-control",
    name: "Pest Control",
    icon: "🐜",
    bgImage: "assets/images/pest-control-realistic.jpg",
    subServices: ["General Pest Control", "Termite Control", "Cockroach Control"]
  },
  {
    id: "painting",
    name: "Painting",
    icon: "🎨",
    bgImage: "https://images.unsplash.com/photo-1562259949-e8e7689d7828?auto=format&fit=crop&w=900&q=80",
    subServices: ["Painting"]
  },
  {
    id: "carpentry",
    name: "Carpentry",
    icon: "🪚",
    bgImage: "https://images.unsplash.com/photo-1517705008128-361805f42e86?auto=format&fit=crop&w=900&q=80",
    subServices: ["Furniture Repair", "Door Repair / Installation"]
  }
];

  const updatedPopularServices = [
    {
      title: "Full Home Cleaning",
      description: "Complete deep cleaning service for your entire home.",
      price: "₹999",
      rating: "4.9",
      categoryId: "home-cleaning",
      image: "https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=900&q=80"
    },
    {
      title: "Bathroom Cleaning",
      description: "Professional bathroom cleaning for a fresh and hygienic space.",
      price: "₹499",
      rating: "4.8",
      categoryId: "home-cleaning",
      image: "https://images.unsplash.com/photo-1620626011761-996317b8d101?auto=format&fit=crop&w=900&q=80"
    },
    {
      title: "Haircut & Styling",
      description: "Salon-quality haircut and styling services at home.",
      price: "₹399",
      rating: "4.8",
      categoryId: "salon-at-home",
      image: "https://images.unsplash.com/photo-1517832606299-7ae9b720a186?auto=format&fit=crop&w=900&q=80"
    },
    {
      title: "Plumbing Service",
      description: "Quick plumbing assistance for leaks, taps, and fittings.",
      price: "₹299",
      rating: "4.8",
      categoryId: "plumbing",
      image: "https://images.unsplash.com/photo-1621905252507-b35492cc74b4?auto=format&fit=crop&w=900&q=80"
    },
    {
      title: "AC Repair",
      description: "Fast AC servicing and repair by trained professionals.",
      price: "₹799",
      rating: "4.9",
      categoryId: "appliance-repair-installation",
      image: "https://images.unsplash.com/photo-1621905251918-48416bd8575a?auto=format&fit=crop&w=900&q=80"
    },
    {
      title: "Pest Control",
      description: "Reliable pest control to keep your home safe and clean.",
      price: "₹899",
      rating: "4.8",
      categoryId: "pest-control",
      image: "assets/images/pest-control-realistic.jpg"
    }
  ];

  const updatedProviders = [
    {
      id: "cleanpro-service",
      name: "Cleanpro Service",
      category: "home-cleaning",
      subServices: ["Full Home Cleaning"],
      years: 8,
      rating: 4.9,
      reviews: 487,
      distance: "2.1 km",
      startingPrice: 999,
      location: "Chennai, Tamil Nadu",
      jobsDone: 1217,
      availableToday: true,
      verified: true,
      image: "https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=900&q=80"
    },
    {
      id: "fresh-space-cleaning",
      name: "Fresh Space Cleaning",
      category: "home-cleaning",
      subServices: ["Kitchen Cleaning"],
      years: 6,
      rating: 4.8,
      reviews: 392,
      distance: "3.0 km",
      startingPrice: 699,
      location: "Chennai, Tamil Nadu",
      jobsDone: 932,
      availableToday: true,
      verified: true,
      image: "https://images.unsplash.com/photo-1563453392212-326f5e854473?auto=format&fit=crop&w=900&q=80"
    },
    {
      id: "urban-shine-cleaner",
      name: "Urban Shine Cleaner",
      category: "home-cleaning",
      subServices: ["Bathroom Cleaning"],
      years: 5,
      rating: 4.7,
      reviews: 301,
      distance: "1.9 km",
      startingPrice: 499,
      location: "Chennai, Tamil Nadu",
      jobsDone: 743,
      availableToday: false,
      verified: true,
      image: "https://images.unsplash.com/photo-1527515637462-cff94eecc1ac?auto=format&fit=crop&w=900&q=80"
    },
    {
      id: "sparkle-home-care",
      name: "Sparkle Home Care",
      category: "home-cleaning",
      subServices: ["Full Home Cleaning", "Bathroom Cleaning"],
      years: 7,
      rating: 4.8,
      reviews: 418,
      distance: "2.6 km",
      startingPrice: 899,
      location: "Chennai, Tamil Nadu",
      jobsDone: 1083,
      availableToday: true,
      verified: true,
      image: "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=900&q=80"
    },

    {
      id: "beauty-express",
      name: "Beauty Express",
      category: "salon-at-home",
      subServices: ["Haircut & Styling"],
      years: 5,
      rating: 4.8,
      reviews: 256,
      distance: "2.0 km",
      startingPrice: 399,
      location: "Chennai, Tamil Nadu",
      jobsDone: 624,
      availableToday: true,
      verified: true,
      image: "https://images.unsplash.com/photo-1521590832167-7bcbfaa6381f?auto=format&fit=crop&w=900&q=80"
    },
    {
      id: "glamour-at-doorstep",
      name: "Glamour At Doorstep",
      category: "salon-at-home",
      subServices: ["Facial & Cleanup"],
      years: 7,
      rating: 4.9,
      reviews: 381,
      distance: "1.5 km",
      startingPrice: 599,
      location: "Chennai, Tamil Nadu",
      jobsDone: 802,
      availableToday: true,
      verified: true,
      image: "https://images.unsplash.com/photo-1560066984-138dadb4c035?auto=format&fit=crop&w=900&q=80"
    },
    {
      id: "royal-beauty-services",
      name: "Royal Beauty Services",
      category: "salon-at-home",
      subServices: ["Manicure & Pedicure"],
      years: 6,
      rating: 4.7,
      reviews: 275,
      distance: "2.9 km",
      startingPrice: 499,
      location: "Chennai, Tamil Nadu",
      jobsDone: 671,
      availableToday: false,
      verified: true,
      image: "https://images.unsplash.com/photo-1515377905703-c4788e51af15?auto=format&fit=crop&w=900&q=80"
    },
    {
      id: "stylehub-home-salon",
      name: "StyleHub Home Salon",
      category: "salon-at-home",
      subServices: ["Haircut & Styling", "Facial & Cleanup"],
      years: 8,
      rating: 4.9,
      reviews: 420,
      distance: "3.4 km",
      startingPrice: 699,
      location: "Chennai, Tamil Nadu",
      jobsDone: 1010,
      availableToday: true,
      verified: true,
      image: "https://images.unsplash.com/photo-1487412912498-0447578fcca8?auto=format&fit=crop&w=900&q=80"
    },
    {
      id: "elegance-home-spa",
      name: "Elegance Home Spa",
      category: "salon-at-home",
      subServices: ["Facial & Cleanup", "Manicure & Pedicure"],
      years: 5,
      rating: 4.8,
      reviews: 288,
      distance: "2.4 km",
      startingPrice: 549,
      location: "Chennai, Tamil Nadu",
      jobsDone: 700,
      availableToday: true,
      verified: true,
      image: "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=900&q=80"
    },

    {
      id: "drainmaster-solutions",
      name: "DrainMaster Solutions",
      category: "plumbing",
      subServices: ["Plumbing"],
      years: 8,
      rating: 4.9,
      reviews: 487,
      distance: "2.8 km",
      startingPrice: 399,
      location: "Chennai, Tamil Nadu",
      jobsDone: 1217,
      availableToday: true,
      verified: true,
      image: "https://images.unsplash.com/photo-1585704032915-c3400ca199e7?auto=format&fit=crop&w=900&q=80"
    },
    {
      id: "pipepro-services",
      name: "PipePro Services",
      category: "plumbing",
      subServices: ["Plumbing"],
      years: 6,
      rating: 4.8,
      reviews: 398,
      distance: "3.2 km",
      startingPrice: 349,
      location: "Chennai, Tamil Nadu",
      jobsDone: 968,
      availableToday: true,
      verified: true,
      image: "https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?auto=format&fit=crop&w=900&q=80"
    },
    {
      id: "aquatech-plumbers",
      name: "AquaTech Plumbers",
      category: "plumbing",
      subServices: ["Plumbing"],
      years: 7,
      rating: 4.8,
      reviews: 421,
      distance: "2.3 km",
      startingPrice: 379,
      location: "Chennai, Tamil Nadu",
      jobsDone: 1034,
      availableToday: true,
      verified: true,
      image: "https://images.unsplash.com/photo-1621905252507-b35492cc74b4?auto=format&fit=crop&w=900&q=80"
    },
    {
      id: "quickfix-plumbing",
      name: "QuickFix Plumbing",
      category: "plumbing",
      subServices: ["Plumbing"],
      years: 5,
      rating: 4.7,
      reviews: 312,
      distance: "1.5 km",
      startingPrice: 299,
      location: "Chennai, Tamil Nadu",
      jobsDone: 811,
      availableToday: true,
      verified: true,
      image: "https://images.unsplash.com/photo-1598514983318-2f64f8f4796c?auto=format&fit=crop&w=900&q=80"
    },

    {
      id: "brightwire-solutions",
      name: "BrightWire Solutions",
      category: "electrician",
      subServices: ["Electrician"],
      years: 8,
      rating: 4.9,
      reviews: 442,
      distance: "2.0 km",
      startingPrice: 399,
      location: "Chennai, Tamil Nadu",
      jobsDone: 1131,
      availableToday: true,
      verified: true,
      image: "https://images.unsplash.com/photo-1621905251189-08b45d6a269e?auto=format&fit=crop&w=900&q=80"
    },
    {
      id: "currentcare-electrician",
      name: "CurrentCare Electrician",
      category: "electrician",
      subServices: ["Electrician"],
      years: 6,
      rating: 4.8,
      reviews: 370,
      distance: "2.6 km",
      startingPrice: 349,
      location: "Chennai, Tamil Nadu",
      jobsDone: 956,
      availableToday: true,
      verified: true,
      image: "https://images.unsplash.com/photo-1555963966-b7ae5404b6ed?auto=format&fit=crop&w=900&q=80"
    },
    {
      id: "powerfix-electrician",
      name: "PowerFix Electrician",
      category: "electrician",
      subServices: ["Electrician"],
      years: 7,
      rating: 4.8,
      reviews: 418,
      distance: "1.8 km",
      startingPrice: 379,
      location: "Chennai, Tamil Nadu",
      jobsDone: 1015,
      availableToday: false,
      verified: true,
      image: "https://images.unsplash.com/photo-1517048676732-d65bc937f952?auto=format&fit=crop&w=900&q=80"
    },
    {
      id: "spark-electric-service",
      name: "Spark Electric Service",
      category: "electrician",
      subServices: ["Electrician"],
      years: 5,
      rating: 4.7,
      reviews: 290,
      distance: "3.1 km",
      startingPrice: 299,
      location: "Chennai, Tamil Nadu",
      jobsDone: 704,
      availableToday: true,
      verified: true,
      image: "https://images.unsplash.com/photo-1621905251189-08b45d6a269e?auto=format&fit=crop&w=900&q=80"
    },
    {
      id: "voltmaster-electric",
      name: "VoltMaster Electric",
      category: "electrician",
      subServices: ["Electrician"],
      years: 9,
      rating: 4.9,
      reviews: 501,
      distance: "2.7 km",
      startingPrice: 449,
      location: "Chennai, Tamil Nadu",
      jobsDone: 1308,
      availableToday: true,
      verified: true,
      image: "https://images.unsplash.com/photo-1544724569-5f546fd6f2b5?auto=format&fit=crop&w=900&q=80"
    },

    {
      id: "allfix-appliances",
      name: "AllFix Appliances",
      category: "appliance-repair-installation",
      subServices: ["Washing Machine", "Refrigerator"],
      years: 8,
      rating: 4.8,
      reviews: 410,
      distance: "2.2 km",
      startingPrice: 499,
      location: "Chennai, Tamil Nadu",
      jobsDone: 1077,
      availableToday: true,
      verified: true,
      image: "https://images.unsplash.com/photo-1517048676732-d65bc937f952?auto=format&fit=crop&w=900&q=80"
    },
    {
      id: "coolcare-ac-services",
      name: "CoolCare AC Services",
      category: "appliance-repair-installation",
      subServices: ["AC"],
      years: 7,
      rating: 4.9,
      reviews: 439,
      distance: "3.0 km",
      startingPrice: 799,
      location: "Chennai, Tamil Nadu",
      jobsDone: 1120,
      availableToday: true,
      verified: true,
      image: "https://images.unsplash.com/photo-1621905251918-48416bd8575a?auto=format&fit=crop&w=900&q=80"
    },
    {
      id: "digitech-solutions",
      name: "DigiTech Solutions",
      category: "appliance-repair-installation",
      subServices: ["Laptop/Desktop"],
      years: 6,
      rating: 4.7,
      reviews: 285,
      distance: "1.7 km",
      startingPrice: 649,
      location: "Chennai, Tamil Nadu",
      jobsDone: 688,
      availableToday: true,
      verified: true,
      image: "https://images.unsplash.com/photo-1517430816045-df4b7de11d1d?auto=format&fit=crop&w=900&q=80"
    },
    {
      id: "homeapp-repair-pro",
      name: "HomeApp Repair Pro",
      category: "appliance-repair-installation",
      subServices: ["TV", "Geyser", "Chimney"],
      years: 5,
      rating: 4.7,
      reviews: 260,
      distance: "2.9 km",
      startingPrice: 399,
      location: "Chennai, Tamil Nadu",
      jobsDone: 640,
      availableToday: false,
      verified: true,
      image: "https://images.unsplash.com/photo-1571171637578-41bc2dd41cd2?auto=format&fit=crop&w=900&q=80"
    },
    {
      id: "quickrepair-services",
      name: "QuickRepair Services",
      category: "appliance-repair-installation",
      subServices: ["TV", "Washing Machine"],
      years: 6,
      rating: 4.8,
      reviews: 320,
      distance: "2.5 km",
      startingPrice: 449,
      location: "Chennai, Tamil Nadu",
      jobsDone: 760,
      availableToday: true,
      verified: true,
      image: "https://images.unsplash.com/photo-1581092795360-fd1ca04f0952?auto=format&fit=crop&w=900&q=80"
    },
    {
      id: "techfix-appliances",
      name: "TechFix Appliances",
      category: "appliance-repair-installation",
      subServices: ["Refrigerator", "AC", "Chimney"],
      years: 8,
      rating: 4.9,
      reviews: 451,
      distance: "3.3 km",
      startingPrice: 549,
      location: "Chennai, Tamil Nadu",
      jobsDone: 1184,
      availableToday: true,
      verified: true,
      image: "assets/images/appliance-repair-realistic.jpg"
    },

    {
      id: "bugbusters-pro",
      name: "BugBusters Pro",
      category: "pest-control",
      subServices: ["General Pest Control"],
      years: 8,
      rating: 4.8,
      reviews: 405,
      distance: "2.0 km",
      startingPrice: 899,
      location: "Chennai, Tamil Nadu",
      jobsDone: 1040,
      availableToday: true,
      verified: true,
      image: "assets/images/pest-control-realistic.jpg"
    },
    {
      id: "greenshield-pest-control",
      name: "GreenShield Pest Control",
      category: "pest-control",
      subServices: ["Termite Control"],
      years: 7,
      rating: 4.8,
      reviews: 372,
      distance: "2.8 km",
      startingPrice: 1199,
      location: "Chennai, Tamil Nadu",
      jobsDone: 920,
      availableToday: true,
      verified: true,
      image: "https://images.unsplash.com/photo-1517048676732-d65bc937f952?auto=format&fit=crop&w=900&q=80"
    },
    {
      id: "pestguard-services",
      name: "PestGuard Services",
      category: "pest-control",
      subServices: ["General Pest Control", "Cockroach Control"],
      years: 9,
      rating: 4.9,
      reviews: 486,
      distance: "1.9 km",
      startingPrice: 999,
      location: "Chennai, Tamil Nadu",
      jobsDone: 1295,
      availableToday: true,
      verified: true,
      image: "https://images.unsplash.com/photo-1626908013351-800ddd734b8a?auto=format&fit=crop&w=900&q=80"
    },
    {
      id: "safehome-pest-care",
      name: "SafeHome Pest Care",
      category: "pest-control",
      subServices: ["Termite Control", "General Pest Control"],
      years: 5,
      rating: 4.7,
      reviews: 248,
      distance: "2.7 km",
      startingPrice: 849,
      location: "Chennai, Tamil Nadu",
      jobsDone: 610,
      availableToday: true,
      verified: true,
      image: "https://images.unsplash.com/photo-1502740479091-635887520276?auto=format&fit=crop&w=900&q=80"
    },

    {
      id: "brushmasters-pro",
      name: "BrushMasters Pro",
      category: "painting",
      subServices: ["Painting"],
      years: 8,
      rating: 4.8,
      reviews: 395,
      distance: "2.4 km",
      startingPrice: 1499,
      location: "Chennai, Tamil Nadu",
      jobsDone: 980,
      availableToday: true,
      verified: true,
      image: "https://images.unsplash.com/photo-1562259949-e8e7689d7828?auto=format&fit=crop&w=900&q=80"
    },
    {
      id: "colorcraft-painters",
      name: "ColorCraft Painters",
      category: "painting",
      subServices: ["Painting"],
      years: 7,
      rating: 4.7,
      reviews: 310,
      distance: "3.2 km",
      startingPrice: 1399,
      location: "Chennai, Tamil Nadu",
      jobsDone: 760,
      availableToday: false,
      verified: true,
      image: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=900&q=80"
    },
    {
      id: "elite-painting-services",
      name: "Elite Painting Services",
      category: "painting",
      subServices: ["Painting"],
      years: 9,
      rating: 4.9,
      reviews: 452,
      distance: "2.1 km",
      startingPrice: 1599,
      location: "Chennai, Tamil Nadu",
      jobsDone: 1180,
      availableToday: true,
      verified: true,
      image: "https://images.unsplash.com/photo-1599696848652-f0ff23bc911f?auto=format&fit=crop&w=900&q=80"
    },
    {
      id: "homeglow-painters",
      name: "HomeGlow Painters",
      category: "painting",
      subServices: ["Painting"],
      years: 6,
      rating: 4.8,
      reviews: 298,
      distance: "1.8 km",
      startingPrice: 1299,
      location: "Chennai, Tamil Nadu",
      jobsDone: 703,
      availableToday: true,
      verified: true,
      image: "https://images.unsplash.com/photo-1556911220-bff31c812dba?auto=format&fit=crop&w=900&q=80"
    },
    {
      id: "perfect-finish-painting",
      name: "Perfect Finish Painting",
      category: "painting",
      subServices: ["Painting"],
      years: 5,
      rating: 4.7,
      reviews: 244,
      distance: "3.4 km",
      startingPrice: 1199,
      location: "Chennai, Tamil Nadu",
      jobsDone: 598,
      availableToday: true,
      verified: true,
      image: "https://images.unsplash.com/photo-1562259949-e8e7689d7828?auto=format&fit=crop&w=900&q=80"
    },

    {
      id: "carpenter-plus",
      name: "Carpenter Plus",
      category: "carpentry",
      subServices: ["Door Repair / Installation"],
      years: 7,
      rating: 4.8,
      reviews: 318,
      distance: "2.5 km",
      startingPrice: 499,
      location: "Chennai, Tamil Nadu",
      jobsDone: 820,
      availableToday: true,
      verified: true,
      image: "https://images.unsplash.com/photo-1504148455328-c376907d081c?auto=format&fit=crop&w=900&q=80"
    },
    {
      id: "expert-woodworks",
      name: "Expert WoodWorks",
      category: "carpentry",
      subServices: ["Furniture Repair"],
      years: 8,
      rating: 4.9,
      reviews: 401,
      distance: "1.9 km",
      startingPrice: 599,
      location: "Chennai, Tamil Nadu",
      jobsDone: 1033,
      availableToday: true,
      verified: true,
      image: "https://images.unsplash.com/photo-1517705008128-361805f42e86?auto=format&fit=crop&w=900&q=80"
    },
    {
      id: "fixit-carpentry",
      name: "FixIt Carpentry",
      category: "carpentry",
      subServices: ["Door Repair / Installation", "Furniture Repair"],
      years: 6,
      rating: 4.8,
      reviews: 337,
      distance: "2.8 km",
      startingPrice: 549,
      location: "Chennai, Tamil Nadu",
      jobsDone: 870,
      availableToday: false,
      verified: true,
      image: "https://images.unsplash.com/photo-1513467655676-561b7d489a88?auto=format&fit=crop&w=900&q=80"
    },
    {
      id: "mastercraft-services",
      name: "MasterCraft Services",
      category: "carpentry",
      subServices: ["Furniture Repair"],
      years: 9,
      rating: 4.9,
      reviews: 470,
      distance: "3.0 km",
      startingPrice: 649,
      location: "Chennai, Tamil Nadu",
      jobsDone: 1210,
      availableToday: true,
      verified: true,
      image: "https://images.unsplash.com/photo-1504148455328-c376907d081c?auto=format&fit=crop&w=900&q=80"
    },
    {
      id: "woodcraft-repair",
      name: "WoodCraft Repair",
      category: "carpentry",
      subServices: ["Furniture Repair", "Door Repair / Installation"],
      years: 5,
      rating: 4.7,
      reviews: 262,
      distance: "1.6 km",
      startingPrice: 449,
      location: "Chennai, Tamil Nadu",
      jobsDone: 622,
      availableToday: true,
      verified: true,
      image: "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=900&q=80"
    }
  ];

  const finalData = {
    ...existingData,
    categories: updatedCategories,
    popularServices: updatedPopularServices,
    providers: updatedProviders
  };

  localStorage.setItem("serveEaseData", JSON.stringify(finalData));
})();